[input]
base_directory = "content"
html_selector = "main"
url_prefix = ""

[[input.files]]
path = "pages/About.md"
url = "/pages/about.html"
title = "About"

[[input.files]]
path = "pages/CVEs.md"
url = "/pages/cves.html"
title = "CVEs"

[[input.files]]
path = "pages/Presentations.md"
url = "/pages/presentations-and-blog-posts.html"
title = "Presentations and Blog posts"

[output]
debug = true
